version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      NODE_ENV: development
      REACT_APP_API_BASE_URL: "http://localhost:3001"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    command: npm start

volumes:
  mongo_data:
